package main

import (
	"fmt"
	"os"

	handler "huskyholdem/adapters/handler/http"
	userAdapter "huskyholdem/adapters/user"
	autils "huskyholdem/adapters/utils"
	service "huskyholdem/service"

	_ "github.com/lib/pq"

	"github.com/joho/godotenv"
)

// @title HuskyHoldem API documentation
// @version 1.0.0
//
// @description This is Huskyholdem backend services' API written in Go using Gin web framework with documents generated by Swagger.
//
// @contact.name Peter Bagas
// @contact.url	huskyholdem.com
// @contact.email admin@huskyholdem.com
//
// @host localhost:8080
// @BasePath /v1
func main() {
	err := godotenv.Load()
	if err != nil {
		fmt.Println("Error loading .env file")
		os.Exit(1)
	}
	port := os.Getenv("PORT")

	var (
		host     = os.Getenv("HOST")
		dbport   = os.Getenv("POSTGRESS_PORT_DEVELOPMENT")
		user     = os.Getenv("POSTGRES_USER_DEVELOPMENT")
		password = os.Getenv("POSTGRES_PASSWORD_DEVELOPMENT")
		dbname   = os.Getenv("POSTGRES_DB_DEVELOPMENT")
	)

	userPostgres := autils.NewPostgressDb(host, dbport, user, password, dbname)
	userCacheClient := autils.NewRedisCache()
	if userCacheClient == nil {
		fmt.Println("Unable to connect to redis")
		os.Exit(1)
	}
	fmt.Println("Successfully connected to redis")

	db, err := userPostgres.Connect()
	if err != nil {
		fmt.Println("Unable to connect to database: " + err.Error())
		os.Exit(1)
	}
	fmt.Println("Successfully connected to database")
	defer userPostgres.Close(db)

	userRepo := userAdapter.NewUserRepository(db)
	userCache := userAdapter.NewUserCache(userCacheClient)

	userService := service.NewUserService(userRepo, userCache)

	pingHandler := handler.NewPingHandler()
	authHandler := handler.NewAuthHandler(userService)

	router, err := handler.NewRouter(pingHandler, authHandler)
	if err != nil {
		fmt.Println("Unable to start application: " + err.Error())
		os.Exit(1)
	}

	err = router.Run(":" + port)
	if err != nil {
		fmt.Println("Unable to start http: " + err.Error())
		os.Exit(1)
	}
}
