package main

import (
	"fmt"
	handler "huskyholdem/handler/http"
	"os"

	"github.com/joho/godotenv"
)

// @title HuskyHoldem API documentation
// @version 1.0.0
//
// @description This is Huskyholdem backend services' API written in Go using Gin web framework with documents generated by Swagger.
//
// @contact.name Peter Bagas
// @contact.url	huskyholdem.com
// @contact.email admin@huskyholdem.com
//
// @host localhost:5000
// @BasePath /v1
func main() {
	err := godotenv.Load()
	if err != nil {
		fmt.Println("Error loading .env file")
		os.Exit(1)
	}
	port := os.Getenv("PORT")
	pingHandler := handler.NewPingHandler()

	router, err := handler.NewRouter(pingHandler)
	if err != nil {
		fmt.Println("Unable to start application: " + err.Error())
		os.Exit(1)
	}

	err = router.Run(":" + port)
	if err != nil {
		fmt.Println("Unable to start http: " + err.Error())
		os.Exit(1)
	}
}
