// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Peter Bagas",
            "url": "huskyholdem.com",
            "email": "admin@huskyholdem.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "If server is healthy, it will return \"hooray!\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Misc"
                ],
                "summary": "Check server health",
                "responses": {
                    "200": {
                        "description": "hooray!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping/env": {
            "get": {
                "description": "Return environment variables if in development mode",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Misc"
                ],
                "summary": "Get environment variables",
                "responses": {
                    "200": {
                        "description": "Environment variables",
                        "schema": {
                            "$ref": "#/definitions/utils.EnvResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Forbidden to access in production",
                        "schema": {
                            "$ref": "#/definitions/utils.errorResponseMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "utils.EnvResponseMessage": {
            "type": "object",
            "properties": {
                "allowedOrigins": {
                    "type": "string",
                    "example": "http://localhost:3000"
                },
                "enviroment": {
                    "type": "string",
                    "example": "development"
                },
                "port": {
                    "type": "string",
                    "example": "8080"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "utils.errorResponseMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "HuskyHoldem API documentation",
	Description:      "This is Huskyholdem backend services' API written in Go using Gin web framework with documents generated by Swagger.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
